//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMO_DATA_BANKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int Permit_id { get; set; }
        public Nullable<int> Permit_type_id { get; set; }
        public Nullable<int> Person_id { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Province_id { get; set; }
        public Nullable<int> Municipality_id { get; set; }
        public Nullable<int> Barangay_id { get; set; }
    
        public virtual Barangay Barangay { get; set; }
        public virtual Category Category { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Permit_Type Permit_Type { get; set; }
        public virtual Province Province { get; set; }
    }
}
